### ISSUE TITLE
鼠标移到图片上，图片上会出现一横一纵两根滚动条

### ISSUE THREAD

**Issue by phoetry** [Sunnnner/wallhaven_rs#1]
1.1.9版

**Comment by shuangmuaigwu** [comment]
> 1.1.9版

可以截图发一下吗,软件平台式win还是什么?

**Comment by Sunnnner** [comment]
> 1.1.9版

可以截图发一下吗?软件平台是win还是其他的?

**Comment by shuangmuaigwu** [comment]
> 1.1.9版

下载最新版本试一下

**Comment by shuo0261** [comment]
系统：Windows11
版本：Wallpapers_1.1.10_x64_en-US.msi
一样的问题
![1](https://github.com/Sunnnner/wallhaven_rs/assets/104809790/234c4e05-4061-4fbf-8f5a-acd85ac50002)

**Comment by Sunnnner** [comment]
> 系统：Windows11 版本：Wallpapers_1.1.10_x64_en-US.msi 一样的问题 ![1](https://private-user-images.githubusercontent.com/104809790/334364078-234c4e05-4061-4fbf-8f5a-acd85ac50002.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4OTc2NzEsIm5iZiI6MTcxNjg5NzM3MSwicGF0aCI6Ii8xMDQ4MDk3OTAvMzM0MzY0MDc4LTIzNGM0ZTA1LTQwNjEtNGZiZi04ZjVhLWFjZDg1YWM1MDAwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQxMTU2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzU2YzgwZTYxYmYzYTg4MTg5ZjVkMGIxZjkxMjdhZDU2ODRmYzU5MWM5MmE3MmM3MjViOTk0ZDUwMmIzMGRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G_tDtAajTPWHzx7cTMmoqaSa_hWoLaVCCphTFuFZbDg)

已修复
